import timer from './modules/timer';
import menu from './modules/menu';
import modal from './modules/modal';
import regex from './modules/regex';
import tabs from './modules/tabs';
timer('31 december 2021');
menu();
modal();
regex();
tabs();